# Generated by Django 5.2 on 2025-04-27 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('provider', models.ForeignKey(db_column='provider', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.status')),
            ],
            options={
                'db_table': 'connection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('max_connections', models.IntegerField()),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization')),
            ],
            options={
                'db_table': 'pole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PoleLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('pole_a', models.ForeignKey(db_column='pole_a', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.pole')),
                ('pole_b', models.ForeignKey(db_column='pole_b', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pole_b', to='connect_hub.pole')),
            ],
            options={
                'db_table': 'pole_link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConnectionLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('connection', models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.connection')),
                ('pole_link', models.ForeignKey(db_column='pole_link', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.polelink')),
            ],
            options={
                'db_table': 'connection_links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('accept_status', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('connection', models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.connection')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.status')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.userinformation')),
            ],
            options={
                'db_table': 'connection_history',
                'managed': True,
            },
        ),
    ]
