# Generated by Django 5.2 on 2025-04-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0002_contacts_restorationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='index',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='building',
            field=models.IntegerField(),
        ),
    ]
