# Generated by Django 5.2 on 2025-04-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0003_contacts_index_alter_contacts_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='index',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pole',
            name='building',
            field=models.IntegerField(),
        ),
    ]
