# Generated by Django 5.2 on 2025-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0004_pole_index_alter_pole_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
