# Generated by Django 5.2 on 2025-04-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0005_contacts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
