# Generated by Django 5.2 on 2025-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0006_alter_restorationrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationrequest',
            name='status',
            field=models.CharField(default='Ожидание', max_length=50),
        ),
    ]
