# Generated by Django 5.2 on 2025-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0007_alter_restorationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='accept_status',
            field=models.CharField(default='Ожидание', max_length=20),
        ),
    ]
