# Generated by Django 5.2 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0008_alter_userinformation_accept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
