# Generated by Django 5.2 on 2025-05-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0009_alter_userinformation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pole',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
