# Generated by Django 5.2 on 2025-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0010_alter_pole_latitude_alter_pole_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polelink',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
