# Generated by Django 5.2 on 2025-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0011_alter_polelink_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
