# Generated by Django 5.2 on 2025-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0012_alter_connection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
