# Generated by Django 5.2 on 2025-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0013_alter_connection_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
