# Generated by Django 5.2 on 2025-05-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0014_alter_connectionhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pole_a_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='pole_b_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionhistory',
            name='pole_a_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionhistory',
            name='pole_b_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='connection',
            field=models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_links', to='connect_hub.connection'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='pole_link',
            field=models.ForeignKey(db_column='pole_link', on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_links', to='connect_hub.polelink'),
        ),
    ]
