# Generated by Django 5.2 on 2025-05-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0015_connection_pole_a_answer_connection_pole_b_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'managed': True, 'ordering': ['updated_at', 'created_at'], 'verbose_name': 'Подключение', 'verbose_name_plural': 'Подключения'},
        ),
        migrations.AlterModelOptions(
            name='connectionhistory',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'История подключений', 'verbose_name_plural': 'История подключений'},
        ),
        migrations.AlterModelOptions(
            name='connectionlinks',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Соединение в подключении', 'verbose_name_plural': 'Соединения в подключении'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='pole',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Опора', 'verbose_name_plural': 'Опоры'},
        ),
        migrations.AlterModelOptions(
            name='polelink',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Связь опор', 'verbose_name_plural': 'Связи опор'},
        ),
        migrations.AlterModelOptions(
            name='restorationrequest',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'Запрос на восстановление', 'verbose_name_plural': 'Запросы на восстановление'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователе'},
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='pole_a_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по первой опоре'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='pole_b_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по второй опоре'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(db_column='provider', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization', verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='connection',
            field=models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.connection', verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='pole_a_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по первой опоре'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='pole_b_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по второй опоре'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.userinformation', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='connection',
            field=models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_links', to='connect_hub.connection', verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='pole_link',
            field=models.ForeignKey(db_column='pole_link', on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_links', to='connect_hub.polelink', verbose_name='Связь опор'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='building',
            field=models.IntegerField(verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='index',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='building',
            field=models.IntegerField(verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='index',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='max_connections',
            field=models.IntegerField(verbose_name='Максимальное количество подключений'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='polelink',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='polelink',
            name='pole_a',
            field=models.ForeignKey(db_column='pole_a', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.pole', verbose_name='Первая опора'),
        ),
        migrations.AlterField(
            model_name='polelink',
            name='pole_b',
            field=models.ForeignKey(db_column='pole_b', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pole_b', to='connect_hub.pole', verbose_name='Вторая опора'),
        ),
        migrations.AlterField(
            model_name='restorationrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='restorationrequest',
            name='status',
            field=models.CharField(default='Ожидание', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='accept_status',
            field=models.CharField(default='Ожидание', max_length=20, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='organization',
            field=models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone_num',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
