# Generated by Django 5.2 on 2025-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0016_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('accept', 'Принятно'), ('rejected', 'Отклонено')], default='Ожидание', max_length=50, verbose_name='Статус'),
        ),
    ]
