# Generated by Django 5.2 on 2025-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0017_alter_restorationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('accept', 'Принято'), ('rejected', 'Отклонено')], default='Ожидание', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='accept_status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('accept', 'Принято'), ('rejected', 'Отклонено')], default='Ожидание', max_length=20, verbose_name='Статус подтверждения'),
        ),
    ]
