# Generated by Django 5.2 on 2025-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0018_alter_restorationrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='type',
            field=models.CharField(choices=[('mainline provider', 'магистральный провайдер'), ('grid company', 'электросетевая компания')], max_length=50, verbose_name='Тип организации'),
        ),
    ]
