# Generated by Django 5.2 on 2025-05-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0019_alter_userinformation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorationrequest',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Ожидание', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='accept_status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено')], default='Ожидание', max_length=20, verbose_name='Статус подтверждения'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='type',
            field=models.CharField(choices=[('магистральный провайдер', 'магистральный провайдер'), ('электросетевая компания', 'электросетевая компания')], max_length=50, verbose_name='Тип организации'),
        ),
    ]
