# Generated by Django 5.2 on 2025-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0020_alter_restorationrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('магистральный провайдер', 'магистральный провайдер'), ('электросетевая компания', 'электросетевая компания')], max_length=50, verbose_name='Тип'),
        ),
    ]
