# Generated by Django 5.2 on 2025-05-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0021_alter_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
