# Generated by Django 5.2 on 2025-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0022_alter_connection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'managed': True, 'ordering': ['-created_at', 'id'], 'verbose_name': 'Подключение', 'verbose_name_plural': 'Подключения'},
        ),
        migrations.AlterModelOptions(
            name='connectionhistory',
            options={'managed': True, 'ordering': ['date', 'id'], 'verbose_name': 'История подключения', 'verbose_name_plural': 'История подключений'},
        ),
        migrations.AlterModelOptions(
            name='connectionlinks',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Связи опор в подключении', 'verbose_name_plural': 'Связи опор в подключениях'},
        ),
        migrations.AlterModelOptions(
            name='restorationrequest',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Заявка на восстановление', 'verbose_name_plural': 'Заявки на восстановление'},
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
