# Generated by Django 5.2 on 2025-05-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0023_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='pole_a_answer',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='pole_b_answer',
        ),
        migrations.RemoveField(
            model_name='connectionhistory',
            name='pole_a_answer',
        ),
        migrations.RemoveField(
            model_name='connectionhistory',
            name='pole_b_answer',
        ),
        migrations.AddField(
            model_name='connectionlinks',
            name='pole_a_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по первой опоре'),
        ),
        migrations.AddField(
            model_name='connectionlinks',
            name='pole_b_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ по второй опоре'),
        ),
        migrations.AddField(
            model_name='connectionlinks',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connect_hub.status', verbose_name='Статус'),
        ),
    ]
