# Generated by Django 5.2 on 2026-05-31 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0025_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPoleMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_hub.pole', verbose_name='Опора')),
            ],
            options={
                'verbose_name': 'Сообщение администратора по опоре',
                'verbose_name_plural': 'Сообщения администратора по опорам',
                'db_table': 'admin_pole_message',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
