# Generated by Django 5.2 on 2026-06-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_hub', '0026_adminpolemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(db_column='provider', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.organization', verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='connection',
            field=models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.connection', verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.userinformation', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='connection',
            field=models.ForeignKey(db_column='connection', on_delete=django.db.models.deletion.RESTRICT, related_name='connection_links', to='connect_hub.connection', verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='pole_link',
            field=models.ForeignKey(db_column='pole_link', on_delete=django.db.models.deletion.RESTRICT, related_name='connection_links', to='connect_hub.polelink', verbose_name='Связь опор'),
        ),
        migrations.AlterField(
            model_name='connectionlinks',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.organization', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='polelink',
            name='pole_a',
            field=models.ForeignKey(db_column='pole_a', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.pole', verbose_name='Первая опора'),
        ),
        migrations.AlterField(
            model_name='polelink',
            name='pole_b',
            field=models.ForeignKey(db_column='pole_b', on_delete=django.db.models.deletion.RESTRICT, related_name='pole_b', to='connect_hub.pole', verbose_name='Вторая опора'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='organization',
            field=models.ForeignKey(db_column='organization', on_delete=django.db.models.deletion.RESTRICT, to='connect_hub.organization', verbose_name='Организация'),
        ),
    ]
